In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv("tweet_train_data.csv")

In [22]:
df.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [7]:
df.tail()

,id,keyword,location,text,target
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [9]:
df.columns

Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object')

In [10]:
df

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [23]:
#split the dataset
#from our originial dataframe we want to split into two so we can test it 
from sklearn.model_selection import train_test_split
from autogluon.tabular import TabularDataset, TabularPredictor

In [24]:
#we split 33% into a test set, the larger portion will be used to 
df_train,df_test=train_test_split(df, test_size=0.33,random_state=1)
df_train.shape,df_test.shape

((5100, 5), (2513, 5))

In [25]:
df_test.head()

,id,keyword,location,text,target
3228,4632,emergency%20services,"Sydney, New South Wales",Goulburn man Henry Van Bilsen missing: Emergen...,1
3706,5271,fear,NaN,The things we fear most in organizations--fluc...,0
6957,9982,tsunami,Land Of The Kings,@tsunami_esh ?? hey Esh,0
2887,4149,drown,NaN,@POTUS you until you drown by water entering t...,0
7464,10680,wounds,"cody, austin follows ?*?",Crawling in my skin\nThese wounds they will no...,1

In [26]:
df_train.head()

,id,keyword,location,text,target
7349,10521,wildfire,NaN,Reuters Top News: PHOTOS: The Rocky Fire has g...,1
563,814,battle,NaN,A young German stormtrooper engaged in the Bat...,1
6022,8607,seismic,NaN,29% of #oil and #gas organizations have no rea...,0
4805,6839,loud%20bang,NaN,@Bang_Me_Up_Guk he was ;-; like he was singing...,0
2684,3850,detonation,NaN,Ignition Knock (Detonation) Sensor-Senso Stand...,0

In [27]:
#we need to drop the target column from the test set
test_data = df_test.drop(['target'], axis=1)
test_data.head()

,id,keyword,location,text
3228,4632,emergency%20services,"Sydney, New South Wales",Goulburn man Henry Van Bilsen missing: Emergen...
3706,5271,fear,NaN,The things we fear most in organizations--fluc...
6957,9982,tsunami,Land Of The Kings,@tsunami_esh ?? hey Esh
2887,4149,drown,NaN,@POTUS you until you drown by water entering t...
7464,10680,wounds,"cody, austin follows ?*?",Crawling in my skin\nThese wounds they will no...

In [55]:
df_train

,id,keyword,location,text,target
7349,10521,wildfire,NaN,Reuters Top News: PHOTOS: The Rocky Fire has grown into California's most ... - http://t.co/qwrRfDGXCc #NewsInTweets http://t.co/sstj2bEpqn,1
563,814,battle,NaN,A young German stormtrooper engaged in the Battle of the Somme 1916. [800 ÌÑ 582 ] http://t.co/yxvMifLvc4,1
6022,8607,seismic,NaN,29% of #oil and #gas organizations have no real-time insight on #cyber threats. See how #EY can help http://t.co/qamgvQAFzc,0
4805,6839,loud%20bang,NaN,@Bang_Me_Up_Guk he was ;-; like he was singing so loud ;-;,0
2684,3850,detonation,NaN,Ignition Knock (Detonation) Sensor-Senso Standard KS161 http://t.co/WadPP69LwJ http://t.co/yjTh2nABv5,0
...,...,...,...,...,...
905,1308,bloody,NaN,All I need in this life of sin\nIs just me and my girlfriend\nDown to ride till the bloody end\nJust me and my girlfriend,0
5192,7413,obliterated,NaN,Drunk Meals 101: What To Cook When You're Totally Obliterated http://t.co/QvS7O10bG3,0
3980,5656,flooding,"Kualar Lumpur, Malaysia",Monsoon Flooding Kills Dozens In Myanmar Prompting Calls For Help - http://t.co/r7vPaKlhvI,1
235,335,annihilated,Û¢ Views From The Six Û¢,just completely annihilated cech with paul keegan what a time to be alive,0
5157,7356,obliterate,Purfleet,Whereas Jez will obliterate the national debt - and give lots of new benefits - by simply printing money! Genius! https://t.co/ReffbkVG9R,1

In [39]:
#build a predictor
predictor= TabularPredictor(label ='target').fit(train_data = df_train, verbosity = 2,presets='best_quality')

#continue training the model with additional rounds using the same training data
#predictor.fit(train_data=df_train, verbosity=2, hyperparameters={'NN': {'num_epochs': 10}})

No path specified. Models will be saved in: "AutogluonModels\ag-20240123_152225\"
Presets specified: ['best_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels\ag-20240123_152225\"
AutoGluon Version:  0.8.2
Python Version:     3.9.2
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.19041
Disk Space Avail:   68.63 GB / 255.11 GB (26.9%)
Train Data Rows:    5100
Train Data Columns: 4
Label Column: target
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [1, 0]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    1952.86 MB
	Train Data (Original)  Memory Usage: 1.49 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['text']
			CountVectorizer fit with vocabulary size = 324
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])          : 1 | ['id']
		('object', [])       : 2 | ['keyword', 'location']
		('object', ['text']) : 1 | ['text']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :   2 | ['keyword', 'location']
		('category', ['text_as_category'])  :   1 | ['text']
		('int', [])                         :   1 | ['id']
		('int', ['binned', 'text_special']) :  28 | ['text.char_count', 'text.word_count', 'text.capital_ratio', 'text.lower_ratio', 'text.digit_ratio', ...]
		('int', ['text_ngram'])             : 323 | ['__nlp__.10', '__nlp__.11', '__nlp__.15', '__nlp__.2015', '__nlp__.30', ...]
	8.9s = Fit runtime
	4 features in original data used to generate 355 features in processed data.
	Train Data (Processed) Memory Usage: 3.51 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 9.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ...
	0.7122	 = Validation score   (accuracy)
	0.18s	 = Training   runtime
	0.99s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ...
	0.7116	 = Validation score   (accuracy)
	0.17s	 = Training   runtime
	0.6s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7869	 = Validation score   (accuracy)
	20.35s	 = Training   runtime
	0.47s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7831	 = Validation score   (accuracy)
	19.89s	 = Training   runtime
	0.53s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ...
	0.7463	 = Validation score   (accuracy)
	6.9s	 = Training   runtime
	2.04s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ...
	0.7482	 = Validation score   (accuracy)
	7.31s	 = Training   runtime
	2.56s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7829	 = Validation score   (accuracy)
	222.98s	 = Training   runtime
	0.78s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ...
	0.7592	 = Validation score   (accuracy)
	7.36s	 = Training   runtime
	2.27s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ...
	0.762	 = Validation score   (accuracy)
	7.46s	 = Training   runtime
	2.22s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7494	 = Validation score   (accuracy)
	75.62s	 = Training   runtime
	0.58s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7759	 = Validation score   (accuracy)
	67.42s	 = Training   runtime
	0.56s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.711	 = Validation score   (accuracy)
	104.53s	 = Training   runtime
	0.58s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	0.7857	 = Validation score   (accuracy)
	38.48s	 = Training   runtime
	1.16s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	0.7951	 = Validation score   (accuracy)
	5.83s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 716.09s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels\ag-20240123_152225\")

In [43]:
predictor = TabularPredictor.load("AutogluonModels\\ag-20240123_152225\\")

In [47]:
#shows us how many models autogluon trained to arrive at its conclusion
predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                      model  score_val  pred_time_val    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0       WeightedEnsemble_L2   0.795098      14.177220  508.683264                0.019962           5.827920            2       True         14
1         LightGBMXT_BAG_L1   0.786863       0.469076   20.347039                0.469076          20.347039            1       True          3
2      LightGBMLarge_BAG_L1   0.785686       1.162545   38.482064                1.162545          38.482064            1       True         13
3           LightGBM_BAG_L1   0.783137       0.532752   19.891526                0.532752          19.891526            1       True          4
4           CatBoost_BAG_L1   0.782941       0.779558  222.984800                0.779558         222.984800            1       True          7
5            XGBoost_BAG_L1   0.775882       0.561104   67.416466                0.561104          67.416466            1       True         11
6     ExtraTreesEntr_BAG_L1   0.761961       2.219793    7.458411                2.219793           7.458411            1       True          9
7     ExtraTreesGini_BAG_L1   0.759216       2.268710    7.356345                2.268710           7.356345            1       True          8
8    NeuralNetFastAI_BAG_L1   0.749412       0.575587   75.618606                0.575587          75.618606            1       True         10
9   RandomForestEntr_BAG_L1   0.748235       2.557777    7.307359                2.557777           7.307359            1       True          6
10  RandomForestGini_BAG_L1   0.746275       2.037453    6.902688                2.037453           6.902688            1       True          5
11    KNeighborsUnif_BAG_L1   0.712157       0.991181    0.177978                0.991181           0.177978            1       True          1
12    KNeighborsDist_BAG_L1   0.711569       0.603216    0.165457                0.603216           0.165457            1       True          2
13    NeuralNetTorch_BAG_L1   0.710980       0.577310  104.530668                0.577310         104.530668            1       True         12
Number of models trained: 14
Types of models trained:
{'StackerEnsembleModel_XT', 'StackerEnsembleModel_CatBoost', 'StackerEnsembleModel_NNFastAiTabular', 'StackerEnsembleModel_TabularNeuralNetTorch', 'WeightedEnsembleModel', 'StackerEnsembleModel_LGB', 'StackerEnsembleModel_XGBoost', 'StackerEnsembleModel_RF', 'StackerEnsembleModel_KNN'}
Bagging used: True  (with 8 folds)
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])                    :   2 | ['keyword', 'location']
('category', ['text_as_category'])  :   1 | ['text']
('int', [])                         :   1 | ['id']
('int', ['binned', 'text_special']) :  28 | ['text.char_count', 'text.word_count', 'text.capital_ratio', 'text.lower_ratio', 'text.digit_ratio', ...]
('int', ['text_ngram'])             : 323 | ['__nlp__.10', '__nlp__.11', '__nlp__.15', '__nlp__.2015', '__nlp__.30', ...]
*** End of fit() summary ***

C:\Users\ajibo\AppData\Roaming\Python\Python39\site-packages\autogluon\core\utils\plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"
  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"')

{'model_types': {'KNeighborsUnif_BAG_L1': 'StackerEnsembleModel_KNN',
  'KNeighborsDist_BAG_L1': 'StackerEnsembleModel_KNN',
  'LightGBMXT_BAG_L1': 'StackerEnsembleModel_LGB',
  'LightGBM_BAG_L1': 'StackerEnsembleModel_LGB',
  'RandomForestGini_BAG_L1': 'StackerEnsembleModel_RF',
  'RandomForestEntr_BAG_L1': 'StackerEnsembleModel_RF',
  'CatBoost_BAG_L1': 'StackerEnsembleModel_CatBoost',
  'ExtraTreesGini_BAG_L1': 'StackerEnsembleModel_XT',
  'ExtraTreesEntr_BAG_L1': 'StackerEnsembleModel_XT',
  'NeuralNetFastAI_BAG_L1': 'StackerEnsembleModel_NNFastAiTabular',
  'XGBoost_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBMLarge_BAG_L1': 'StackerEnsembleModel_LGB',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'KNeighborsUnif_BAG_L1': 0.712156862745098,
  'KNeighborsDist_BAG_L1': 0.7115686274509804,
  'LightGBMXT_BAG_L1': 0.7868627450980392,
  'LightGBM_BAG_L1': 0.7831372549019607,
  'RandomForestGini_BAG_L1': 0.7462745098039215,
  'RandomForestEntr_BAG_L1': 0.7482352941176471,
  'CatBoost_BAG_L1': 0.7829411764705883,
  'ExtraTreesGini_BAG_L1': 0.7592156862745097,
  'ExtraTreesEntr_BAG_L1': 0.7619607843137255,
  'NeuralNetFastAI_BAG_L1': 0.7494117647058823,
  'XGBoost_BAG_L1': 0.7758823529411765,
  'NeuralNetTorch_BAG_L1': 0.7109803921568627,
  'LightGBMLarge_BAG_L1': 0.7856862745098039,
  'WeightedEnsemble_L2': 0.7950980392156862},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'KNeighborsUnif_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\KNeighborsUnif_BAG_L1\\',
  'KNeighborsDist_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\KNeighborsDist_BAG_L1\\',
  'LightGBMXT_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\LightGBMXT_BAG_L1\\',
  'LightGBM_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\LightGBM_BAG_L1\\',
  'RandomForestGini_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\RandomForestGini_BAG_L1\\',
  'RandomForestEntr_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\RandomForestEntr_BAG_L1\\',
  'CatBoost_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\CatBoost_BAG_L1\\',
  'ExtraTreesGini_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\ExtraTreesGini_BAG_L1\\',
  'ExtraTreesEntr_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\ExtraTreesEntr_BAG_L1\\',
  'NeuralNetFastAI_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\NeuralNetFastAI_BAG_L1\\',
  'XGBoost_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\XGBoost_BAG_L1\\',
  'NeuralNetTorch_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\NeuralNetTorch_BAG_L1\\',
  'LightGBMLarge_BAG_L1': 'AutogluonModels\\ag-20240123_152225\\models\\LightGBMLarge_BAG_L1\\',
  'WeightedEnsemble_L2': 'AutogluonModels\\ag-20240123_152225\\models\\WeightedEnsemble_L2\\'},
 'model_fit_times': {'KNeighborsUnif_BAG_L1': 0.1779782772064209,
  'KNeighborsDist_BAG_L1': 0.16545701026916504,
  'LightGBMXT_BAG_L1': 20.347039222717285,
  'LightGBM_BAG_L1': 19.891525506973267,
  'RandomForestGini_BAG_L1': 6.9026877880096436,
  'RandomForestEntr_BAG_L1': 7.307359218597412,
  'CatBoost_BAG_L1': 222.98480010032654,
  'ExtraTreesGini_BAG_L1': 7.356345176696777,
  'ExtraTreesEntr_BAG_L1': 7.458410978317261,
  'NeuralNetFastAI_BAG_L1': 75.61860632896423,
  'XGBoost_BAG_L1': 67.41646552085876,
  'NeuralNetTorch_BAG_L1': 104.53066825866699,
  'LightGBMLarge_BAG_L1': 38.48206424713135,
  'WeightedEnsemble_L2': 5.827920198440552},
 'model_pred_times': {'KNeighborsUnif_BAG_L1': 0.9911808967590332,
  'KNeighborsDist_BAG_L1': 0.6032161712646484,
  'LightGBMXT_BAG_L1': 0.46907567977905273,
  'LightGBM_BAG_L1': 0.532752275466919,
  'RandomForestGini_BAG_L1': 2.0374526977539062,
  'RandomForestEntr_BAG_L1': 2.557776927947998,
  'CatBoost_BAG_L1': 0.7795577049255371,
  'ExtraTreesGini_BAG_L1': 2.2687103748321533,
  'ExtraTreesEntr_BAG_L1': 2.219792604446411,
  'NeuralNetFastAI_BAG_L1': 0.5755870342254639,
  'XGBoost_BAG_L1': 0.5611038208007812,
  'NeuralNetTorch_BAG_L1': 0.5773100852966309,
  'LightGBMLarge_BAG_L1': 1.1625447273254395,
  'WeightedEnsemble_L2': 0.019962072372436523},
 'num_bag_folds': 8,
 'max_stack_level': 2,
 'num_classes': 2,
 'model_hyperparams': {'KNeighborsUnif_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'KNeighborsDist_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'LightGBMXT_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'LightGBM_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'RandomForestGini_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'RandomForestEntr_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'CatBoost_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'ExtraTreesGini_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'ExtraTreesEntr_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'NeuralNetFastAI_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'XGBoost_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'NeuralNetTorch_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'LightGBMLarge_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True}},
 'leaderboard':                       model  score_val  pred_time_val    fit_time  \
 0       WeightedEnsemble_L2   0.795098      14.177220  508.683264
 1         LightGBMXT_BAG_L1   0.786863       0.469076   20.347039
 2      LightGBMLarge_BAG_L1   0.785686       1.162545   38.482064
 3           LightGBM_BAG_L1   0.783137       0.532752   19.891526
 4           CatBoost_BAG_L1   0.782941       0.779558  222.984800
 5            XGBoost_BAG_L1   0.775882       0.561104   67.416466
 6     ExtraTreesEntr_BAG_L1   0.761961       2.219793    7.458411
 7     ExtraTreesGini_BAG_L1   0.759216       2.268710    7.356345
 8    NeuralNetFastAI_BAG_L1   0.749412       0.575587   75.618606
 9   RandomForestEntr_BAG_L1   0.748235       2.557777    7.307359
 10  RandomForestGini_BAG_L1   0.746275       2.037453    6.902688
 11    KNeighborsUnif_BAG_L1   0.712157       0.991181    0.177978
 12    KNeighborsDist_BAG_L1   0.711569       0.603216    0.165457
 13    NeuralNetTorch_BAG_L1   0.710980       0.577310  104.530668

     pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
 0                 0.019962           5.827920            2       True
 1                 0.469076          20.347039            1       True
 2                 1.162545          38.482064            1       True
 3                 0.532752          19.891526            1       True
 4                 0.779558         222.984800            1       True
 5                 0.561104          67.416466            1       True
 6                 2.219793           7.458411            1       True
 7                 2.268710           7.356345            1       True
 8                 0.575587          75.618606            1       True
 9                 2.557777           7.307359            1       True
 10                2.037453           6.902688            1       True
 11                0.991181           0.177978            1       True
 12                0.603216           0.165457            1       True
 13                0.577310         104.530668            1       True

     fit_order
 0          14
 1           3
 2          13
 3           4
 4           7
 5          11
 6           9
 7           8
 8          10
 9           6
 10          5
 11          1
 12          2
 13         12  }

In [51]:
#find the best model selected by autogluon
predictor.leaderboard(df_train, silent=True)

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestEntr_BAG_L1,1.000000,0.748235,0.708813,2.557777,7.307359,0.708813,2.557777,7.307359,1,True,6
1,RandomForestGini_BAG_L1,1.000000,0.746275,0.711452,2.037453,6.902688,0.711452,2.037453,6.902688,1,True,5
2,KNeighborsDist_BAG_L1,1.000000,0.711569,0.724822,0.603216,0.165457,0.724822,0.603216,0.165457,1,True,2
3,ExtraTreesGini_BAG_L1,1.000000,0.759216,0.782461,2.268710,7.356345,0.782461,2.268710,7.356345,1,True,8
4,ExtraTreesEntr_BAG_L1,1.000000,0.761961,0.789982,2.219793,7.458411,0.789982,2.219793,7.458411,1,True,9
5,LightGBMLarge_BAG_L1,0.994706,0.785686,2.814684,1.162545,38.482064,2.814684,1.162545,38.482064,1,True,13
6,WeightedEnsemble_L2,0.983529,0.795098,13.346178,14.177220,508.683264,0.031027,0.019962,5.827920,2,True,14
7,LightGBM_BAG_L1,0.926863,0.783137,1.501294,0.532752,19.891526,1.501294,0.532752,19.891526,1,True,4
8,XGBoost_BAG_L1,0.926667,0.775882,2.288061,0.561104,67.416466,2.288061,0.561104,67.416466,1,True,11
9,LightGBMXT_BAG_L1,0.886078,0.786863,1.438666,0.469076,20.347039,1.438666,0.469076,20.347039,1,True,3
10,CatBoost_BAG_L1,0.848627,0.782941,0.453997,0.779558,222.984800,0.453997,0.779558,222.984800,1,True,7
11,NeuralNetTorch_BAG_L1,0.836078,0.710980,1.051950,0.577310,104.530668,1.051950,0.577310,104.530668,1,True,12
12,NeuralNetFastAI_BAG_L1,0.827059,0.749412,2.131852,0.575587,75.618606,2.131852,0.575587,75.618606,1,True,10
13,KNeighborsUnif_BAG_L1,0.798627,0.712157,0.773791,0.991181,0.177978,0.773791,0.991181,0.177978,1,True,1

In [52]:
#check for any feature engineering enhancing
predictor.feature_importance(data=df_train)

Computing feature importance via permutation shuffling for 4 features using 5000 rows with 5 shuffle sets...
	354.99s	= Expected runtime (71.0s per shuffle set)
	302.84s	= Actual runtime (Completed 5 of 5 shuffle sets)

          importance    stddev       p_value  n  p99_high   p99_low
text         0.40064  0.004533  1.966206e-09  5  0.409973  0.391307
keyword      0.06296  0.001135  1.266386e-08  5  0.065297  0.060623
id           0.01268  0.001712  3.895343e-05  5  0.016206  0.009154
location     0.00444  0.000899  1.910308e-04  5  0.006291  0.002589

In [56]:
#we feed the test data to the classifier for prediction and we can store it in a DataFrame
y_pred = predictor.predict(test_data)
y_pred=pd.DataFrame(y_pred,columns=['target'])
y_pred

      target
3228       0
3706       0
6957       0
2887       0
7464       0
...      ...
5312       1
91         1
7163       0
5395       0
7087       0

[2513 rows x 1 columns]

In [57]:
#To understand the evaluation metric ‘accuracy’, let us print the details for it
predictor.evaluate(df_test)

Evaluation: accuracy on test data: 0.8010346199761241
Evaluations on test data:
{
    "accuracy": 0.8010346199761241,
    "balanced_accuracy": 0.7835869680098018,
    "mcc": 0.5860711245274534,
    "roc_auc": 0.8573567539284778,
    "f1": 0.7395833333333333,
    "precision": 0.8086560364464692,
    "recall": 0.6813819577735125
}

{'accuracy': 0.8010346199761241,
 'balanced_accuracy': 0.7835869680098018,
 'mcc': 0.5860711245274534,
 'roc_auc': 0.8573567539284778,
 'f1': 0.7395833333333333,
 'precision': 0.8086560364464692,
 'recall': 0.6813819577735125}

In [58]:
y_pred

      target
3228       0
3706       0
6957       0
2887       0
7464       0
...      ...
5312       1
91         1
7163       0
5395       0
7087       0

[2513 rows x 1 columns]

In [60]:
y_pred.to_csv('tweetPrediction.csv', index=False, encoding='utf-8')
print("dataFrame saved to 'tweetPrediction.csv'")

dataFrame saved to 'tweetPrediction.csv'